### ISSUE TITLE
Trojan Trojan:Script/Wacatac.B!ml detected

### ISSUE THREAD

**Issue by izanamisu** [stream-pi/client#109]
Hi, my virus scanner detected Trojan:Script/Wacatac.B!ml in the stream-pi github.. please remove
![virus](https://user-images.githubusercontent.com/78270523/154930834-1a33ff17-4c84-4338-9a84-5650e20e975d.png)
.

**Comment by rnayabed** [comment]
If this is not a false positive, you have probably installed it from a different source and not from our github page.
Give the EXACT download link of the file you have downloaded!

We plan to introduce fingerprints in the future so that you can also verify with our keys and match if you got the proper file or one that has been manipulated.

**Comment by rnayabed** [comment]
Adding to that, we no longer provide any `.zip` files for Windows installation since 1.0.0 EA+3.
Either this is a false positive, or you have downloaded it from a malicious 3rd party source.

Also, I have scanned the snapshot 2.0.0 client msi and the 1.0.0 EA+3 msi, and 0 threats found by virus total:

[2.0.0 Snapshot Build 66](https://www.virustotal.com/gui/file/77c77de58cc018fb69b9ba09e7e9149b23d0fc6c5c21c88d1417d79fb6c085cb?nocache=1)

[1.0.0 EA+3](https://www.virustotal.com/gui/file/6b36c20fcfad1f85ee9e9eceffde8d90f8f9ff223c9e31f69477fdac835b7624)

Hence, I am closing this issue.

**Comment by rnayabed** [comment]
I have added the signature files for verification and also updated the installation steps by adding steps on how you can verify the authenticity of the builds using GPG.

Any unofficial or 3rd party builds that fail the signature verification are NOT supported. We take absolutely 0 responsibility for 3rd party builds. You must immediately report such malicious builds to us.
