### ISSUE TITLE
Android App Cant Install On This Device

### ISSUE THREAD

**Issue by dchotwolf101** [stream-pi/client#63]
I am running a 64bit os on my phone. I downloaded the client but it just says cant install on this device. I am running Android Version 10.

**Comment by rnayabed** [comment]
Can you say the device name and model?

**Comment by dchotwolf101** [comment]
moto g(7) optimo (XT1952DL)

**Comment by rnayabed** [comment]
I think this is due to the fact that the apk provided is an unsigned one. Some devices do not allow unsigned APKs to be resolved

However that shall be resolved soon after new EA 3 builds are finalised, as future android releases will be hosted on the Google Play Store
________________________________

**Comment by rnayabed** [comment]
@dchotwolf101 can you try installing the latest Ea+4-snapshot APKs or the latest Ea+3 apk ?

**Comment by mckinnon81** [comment]
I am getting the same problem. 

Error showing App not installed. I have tried both the EA 3 and EA 4 Snapshot.

Android: 5.1.1
Samsung Galaxy Tab A

**Comment by rnayabed** [comment]
Closing since no reply for a week. Reply if problem still persists, will reopen this issue
