### ISSUE TITLE
i can't connect my phone to the server on linux

### ISSUE THREAD

**Issue by PaliWasTakn** [stream-pi/client#93]
i installed the stream pi server on my pc running linux using .deb file and the client the same way because i did not know what server/client means. i connected the client to the server on pc and than tried my phone. i disconnected the client but i could not connect my phone. it says: "Connection Error Unable to connect to server. Please check settings and connection and try again" My pc is on ethernet and phone on WiFi. do you think its something about my internet? Please help!

**Comment by rnayabed** [comment]
You need to run the server on your PC and the client on your android phone.

Then you need to have both of them connected to the same network.

After that, youll have to put the IP of your server on your phone's stream-pi client app.

You can get the IP/port combination from the top window bar of the server application 

![image](https://user-images.githubusercontent.com/25760501/141655920-e5403632-f84a-4bc8-b128-0607ef38c21e.png)

**Comment by PaliWasTakn** [comment]
Yes, i did exactly as you said, It just does not want to connect. All is correct  
![image](https://user-images.githubusercontent.com/90306816/141673825-773e6e26-5ccd-4085-be8a-2f864ac83c3c.png)
![WhatsApp Image 2021-11-14 at 10 37 32 AM](https://user-images.githubusercontent.com/90306816/141673859-815481a2-e8ef-43b0-b30c-7074cd777294.jpeg)

**Comment by rnayabed** [comment]
Can you perhaps try with a separate port? There may also be your firewall or something else interfering with the connection.

As a latch ditch effort and if nothing else works, you should try connecting your own phone to your PC via a USB cable, and then turn on USB tethering via your phone. Make sure you restart your stream-pi server in order to get the new list of IPs (in which you will also get the IP for your computer in the new network established between your PC and phone).

**Comment by rnayabed** [comment]
@PaliWasTakn any updates?

**Comment by rnayabed** [comment]
Closing as OP has not replied. Re open if issue persists.
